version: '3.9'
services:
  db:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=SkillSwap
    ports:
      - "5432:5432"
    networks:
      - spring-boot-network
  spring:
    image: skill-swap-app
    container_name: SkillSwapApplication
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - spring-boot-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/SkillSwap
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
networks:
  spring-boot-network:
    driver: bridge
